// Settings:
:idprefix:
:idseparator: -
:toc: macro
:toclevels: 2
:experimental:
//ifdef::env-idea[:status:]
//:status:
//:toc: preamble
//:toclevels: 3
//endif::[]
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:status:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :fire:
:warning-caption: :warning:
endif::[]
//ifdef::env-idea[:toc: right]
ifdef::env-idea[]
:title-page:
:author: Avec112
//:toc-title: toc title
:toc:
:!status:
endif::[]

= Commons Security: Encryption done easy

ifdef::status[]
image:https://img.shields.io/github/actions/workflow/status/Avec112/commons-security/maven.yml?logo=github[Build status]
image:https://img.shields.io/github/actions/workflow/status/Avec112/commons-security/codeql.yml?label=CodeQL&logo=github[CodeQL]
image:https://coveralls.io/repos/github/Avec112/commons-security/badge.svg?branch=master[Coverage, link=https://coveralls.io/github/Avec112/commons-security?branch=master]
image:https://img.shields.io/github/license/avec112/commons-security[License]
image:https://img.shields.io/github/last-commit/Avec112/commons-security[Last Commit]
endif::[]

// ":toc: macro" writes to this one
toc::[]

<<<

== Overview
*Commons Security* is a Java library with several encryption features for `Java 8` or higher build on top of `JCA/JCE` with `BouncyCastle` as provider. The library hides the implementation behind a simple and easy to use API. Typically a simplified API requires that some decisions has been made already, like which algorithm to use, encryption strength, etc. However do not worry, look behind the simplified API and you will find more configuration options.

.Features

* *Asymmetric encryption* and decryption with _public key_ and _private key_. `RSA` is supported.
* *Symmetric encryption* and decryption with one (same) key. `AES/CTR` and `AES/GCM` is supported.
* *Shamir's Secret Sharing* is a way to split a secret into shares. The secret can be recreated by putting the minimum required amount of shares back together.
* *Password Encoder* uses proven algorithms for hashing passwords in a safe and secure way.
* *Digest* or message digest is the result of hashing and is a way to integrity check our data. A typical use case could be to compare content (hashed) with a stored hash to verify if the data has been altered.
* Digital *Signature* and *verification* using RSA keypair and modern `RSASSA-PSS` padding. The user signs data with their _private key_ and others verify the signature with the originator’s _public key_.


You may use the simple delegate class `CryptoUtils` or you can access classes like `RsaCipher`, `AesCipher`, `Shamir`, etc. directly. The latter might give you more options. Implementation alternatives are shown in examples below.

=== Some common classes
This is some common classes used when working with _Symmetric_ and _Asymmetric encryption_ but also _Password Encoding_.

* `PlainText` is a placeholder for unencrypted text. +
`PlainText plainText = new PlainText("My secret plaintext");`
* `CipherText` is a placeholder for encrypted text. +
`CipherText cipherText = new CipherText("ymEIVhbBPhWAIzDx7MalbeLoccwnw=");`
* `Password` is a placeholder for a string (the password) used for either encryption or decryption. +
`Password password = new Password("SecretPassword123!");`
* `PublicKey` holds the _public key_ derived from `java.security.KeyPair` and can be used for encryption or signature verification. +
`PublicKey publicKey = keyPair.getPublicKey();`
* `PrivateKey` holds the _private key_ derived from `java.security.KeyPair` and can be used for decryption or for creating a signature. +
`PrivateKey privateKey = keyPair.getPrivateKey();`

== RSA asymmetric encryption

__RSA__footnote:[https://en.wikipedia.org/wiki/RSA_(cryptosystem)] (Rivest–Shamir–Adleman) is a _public-key_ cryptosystem that is widely used for secure data transmission. In a _public-key_ cryptosystem, the encryption key is public and distinct from the decryption key, which is kept secret (private).

[quote]
It involves the use of two mathematically related keys. The public key (the one that’s known to everybody) and the private key (which is only known by you) are required for encrypting and decrypting the message. The public key can be derived from the private key but not the other way.

Asymmetric encryption use a _public key_ for encryption and a _private_ key for decryption. Useful when you want to
share secrets with others. You may encrypt a file with someone's _public key_, so they will be able to decrypt with
their matching _private key_.

TIP: Used to share small files or text with other users. For large content (more than 117 bytes) use AES symmetric
encryption. The AES secret key can later be shared by using _Public Key Encryption_ like RSA encryption or __Diffie-Hellman__footnote:[https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange].

=== RSA KeyPair

RSA requires a _private key_ and a matching _public key_. Supported key sizes (encryption strength) are `2048`, `3072` (default)
and `4096`.

NOTE: A key size of `3072` bit or higher is recommended for strong security. Key size `1024` is not supported.

TIP: Any secret encrypted with a _public key_ can only be decrypted with the associated _private key_.

[source,java]
.Using `KeyUtils` to generate a `4096` bit `KeyPair`
----
KeyPair keyPair = KeyUtils.generateKeyPair4096();
----
[source,java]
.Alternative
----
RsaCipher rsaCipher = new RsaCipher();
KeyPair keyPair = rsaCipher.generateKeyPair(KeySize.BIT_4096);
----

=== RSA Encryption and Decryption

[source,java]
.RSA encryption and decryption using `CryptoUtils`
----
KeyPair keyPair = CryptoUtils.generateKeyPair4096();
CipherText cipherText = CryptoUtils.rsaEncrypt("My secret", keyPair.getPublicKey());
PlainText plainText = CryptoUtils.rsaDecrypt(cipherText, keyPair.getPrivateKey());
----

[source,java]
.Alternative
----
RsaCipher rsaCipher = new RsaCipher();
KeyPair keyPair = rsaCipher.generateKeyPair(KeySize.BIT_4096);
CipherText cipherText = rsaCipher.encrypt("My secret", keyPair.getPublicKey());
PlainText plainText = rsaCipher.decrypt(cipherText, keyPair.getPrivateKey());
----

== AES symmetric encryption
__The Advanced Encryption Standard__ (AES)footnote:[https://en.wikipedia.org/wiki/Advanced_Encryption_Standard], also known by its original name Rijndael is a specification for the encryption of electronic data established by the U.S. National Institute of Standards and Technology (NIST) in 2001.

[quote]
There’s a single shared key that’s used for encryption and decryption.

TIP: Useful for encryption larger files compared to
asymmetric encryption. A symmetric key can be shared (distributed) by using _RSA public key encryption_, _Diffie-Hellman_ or even
_Sharmir's Secret Sharing_ if needed.

Modes supported: `GCM`, `CTR` +
Strength supported: `128`, `192`, `256`

=== AES Encryption and Decryption

[source,java]
.AES encryption and decryption using `CryptoUtils` with `GCM`@`256`-bit
----
Password password = new Password("SecretPassword123!");
CipherText cipherText = CryptoUtils.aesEncrypt("Secret text", password);
PlainText plainText = CryptoUtils.aesDecrypt(cipherText, password);
----

[source,java]
.Alternative (here as `CTR`@`192`-bit)
----
Password password = new Password("SecretPassword123!");
AesCipher aesCipher = new AesCipher(EncryptionMode.CTR, EncryptionStrength.BIT_192);
h cipherText = aesCipher.encrypt("Secret text", password);
PlainText plainText = aesCipher.decrypt(cipherText, password);
----

== Shamir's Secret Sharing

__Shamir's Secret Sharing__footnote:[https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing] is used to share a secret in a
distributed way, most often to secure other encryption keys. These shares are used to reconstruct the original secret.

To unlock the secret via Shamir's Secret Sharing, a minimum number of shares are needed. This is called the
threshold, and is used to denote the minimum number of shares needed to unlock the secret.

This implementation is based on the work of __Coda Hale__footnote:[https://github.com/codahale] and his project __Shamir__footnote:[https://github.com/codahale/shamir].

[source,java]
.Shamir's Secret Sharing using `CryptoUtils`
----
int totalShares = 5;
int minShares = 2; // threshold
Secret secret = new Secret("Secret text");

// Split the secret into 5 shares
Shares shares = CryptoUtils.getShamirShares(secret, totalShares, minShares);
Share bob = shares.get(0);
Share alice = shares.get(1);

// Reconstruct the secret using any combination of at least `minShares` shares
Secret reconstructed = CryptoUtils.getShamirSecret(bob, alice);
----
NOTE: The API validates invalid configurations such as `threshold < 2` or `threshold > totalShares`.

[source,java]
.Alternative
----
int totalShares = 5;
int minShares = 2; // threshold
Secret secret = new Secret("Secret text");

// Split the secret into 5 shares
Shares shares = Shamir.getShares(secret, totalShares, minShares);
Share bob = shares.get(0);
Share alice = shares.get(1);

// Reconstruct the secret using any combination of at least `minShares` shares
Secret reconstructed = Shamir.getSecret(bob, alice);
----

=== Shamir example
A bank has a vault full of money. The bank's policy requires that nobody should be able to open the vault alone.
Five employees are selected to have access to the vault and there must be at least two (2) employees at any time when opening the vault.

* *Split phase:* Five (5) keys are being distributed. `Bob`, `Alice`, `Eve`, `Tom` and `Lisa` all get one _share_ each using _Shamir's Secret Sharing_ to split the secret into five shares.
* *Join phase:* It's time to open the safe. The requirement is two (2) shares to open the vault. `Bob` and `Alice` bring their shares. By using _Shamir's Secret Sharing_ the shares from both will be joined and the secret recreated.

== Digest (hashing)
_Digest_ or _message digest_ is the result of __hashing__footnote:[https://en.wikipedia.org/wiki/Hash_function] data or content. The hashing is a one-way compression function to convert inputs of different lengths into a fixed-length output (hash value). The default used by this library is `SHA-2`@`SHA-512/256`. It provides 256-bit output with the internal 64-bit strength of SHA-512, combining high security with good performance on modern CPUs. Up to `SHA-2`@`SHA-512` is possible with `JDK 8`. Stronger and newer hashing like `SHA3` is not supported out of the box with `JDK 8`. That would require `JDK 9` or higher. However  __BouncyCastle__footnote:bc[https://www.bouncycastle.org/java.html] has been added as main provider and `SHA-3` is therefore available.

NOTE: SHA-512/256 offers the same collision resistance as SHA-512,
but produces a shorter digest (256 bits) and is faster on 64-bit systems. Other algorithms such as SHA3-256 and SHA3-512 are also supported when using the BouncyCastle provider.

IMPORTANT: Do not use Message Digest for password storage. For that you should use KDFfootnote:kdf[Key Derivation Functions. https://cryptobook.nakov.com/mac-and-key-derivation/kdf-deriving-key-from-password] algorithms like `ARGON2`, `BCRYPT`, `SCRYPT` or `PBKDF2`. Se _Password Encoder_ below.

.Non supported hashing algorithms
The following hashing algorithms are [.underline]#*not*# recommended or included: `MD4`, `MD5`, `SHA-0` and `SHA-1`

.Supported hashing algorithms
[source,java]
----
include::src/main/java/io/github/avec112/security/crypto/digest/DigestAlgorithm.java[tag=hashing-algorithms]
----

.Worth reading
* Read more about __Secure Hash Algorithms__footnote:hash[https://en.wikipedia.org/wiki/Secure_Hash_Algorithms]
* Nice article about __hashing security__footnote:[https://crackstation.net/hashing-security.htm]

=== Example

[source,java]
.Raw bytes
----
final byte[] digest = DigestUtils.digest(data);
----

[source,java]
.Base64 encoded
----
final String digest = DigestUtils.base64Digest(data);
----

[source,java]
.Hex encoded
----
final String digest = DigestUtils.hexDigest(data);
----

[source,java]
.Other hashing algorithms (example `SHA3-384`)
----
final byte[] digest = DigestUtils.digest(data, DigestAlgorithm.SHA3_384);
----

== Password Encoder
Key Derivation Functions (KDF)footnote:kdf[] from a password must be able to stand attacks like *brute-forcing*, *dictionary attacks*, *rainbow attacks* and more. Attempts to reverse hashed password values is common.

`ARGON2`, `BCRYPT`, `SCRYPT` and `PBKDF2` are common algorithms used for password hashing since they are much more robust when attacked.

TIP: `ARGON2` is recommended as the most secure hash algorithm for passwords and is the default implementation for this API.

=== Encoding
A plaintext password should always be encoded in case of a breach. After a password is encoded it may be stored for future matching.

[source,java]
.Supported password encoders
----
include::src/main/java/io/github/avec112/security/crypto/password/PasswordEncoderType.java[lines=3..]
----

[source,java]
.Password encode (default `ARGON2`)
----
final String encodedPassword = PasswordEncoderUtils.encode(password);
----
[source,java]
.Alternative encoding with use of `enum PasswordEncoderType`
----
final String encodedPassword = PasswordEncoderUtils.encode(password, PasswordEncoderType.BCRYPT);
----
=== Matching
When a user is authenticated they must input their password. This plaintext password will be matched against the stored encoded password.

[source,java]
.Password matching (default `ARGON2`)
----
final boolean isMatching = PasswordEncoderUtils.matches(rawPassword, encodedPassword);
----

[source,java]
.Alternative matching with use of `enum PasswordEncoderType`
----
final boolean isMatching = PasswordEncoderUtils.matches(rawPassword, encodedPassword, PasswordEncoderType.BCRYPT);
----

== Signature and verification
A __digital signature__footnote:[https://en.wikipedia.org/wiki/Digital_signature] is a mathematical scheme for verifying the authenticity of digital messages or documents. A valid digital signature, where the prerequisites are satisfied, gives a recipient very strong reason to believe that the message was created by a known sender (authentication), and that the message was not altered in transit.

Commons Security uses `RSASSA-PSS` (SHA-256 with MGF1)footnote:[https://www.encryptionconsulting.com/overview-of-rsassa-pss] — the modern and recommended signature scheme replacing legacy `SHA256withRSA`.

[source,java]
.Signing and verifying data
----
KeyPair keyPair = KeyUtils.generateKeyPair2048();
byte[] signature = SignatureUtils.sign("My data", keyPair.getPrivate());
boolean verified = SignatureUtils.verify(signature, "My data", keyPair.getPublic());
----
TIP: RSASSA-PSS provides probabilistic padding, making it more secure than the traditional PKCS#1 v1.5 (`SHA256withRSA`).


== Recommended reading
* Practical Cryptography for Developersfootnote:[https://cryptobook.nakov.com/] by Svetlin Nakov
* Password1 - Why we moved to 256-bit AES keysfootnote:[https://blog.1password.com/why-we-moved-to-256-bit-aes-keys/] by Jeffrey Goldberg in 2013

== TODO
* Make API fluently as much as possible
* Replacing MultipleMissingArgumentsError with own class without dependency to opentest4j and only throwing/supporting RuntimeException
* Support more algorithms for hashing digestsfootnote:hash[] including password hashing
* Implement support for ECC as option over RSAfootnote:[https://www.globalsign.com/en/blog/elliptic-curve-cryptography]. ECC is faster and stronger than RSA.
* Look into Diffie-Hellman and/or other better key exchange alternatives
* Consider adding support for generating and validation passwords with help of __Passay__footnote:[http://www.passay.org] library
* Consider making this project a library on __Maven Central__footnote:[https://central.sonatype.org/publish/]
