name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build, test, and generate coverage
        run: mvn -B clean verify jacoco:report --file pom.xml

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Upload coverage to Coveralls
        if: github.ref == 'refs/heads/master'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-jacoco: target/site/jacoco/jacoco.xml

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Asciidoctor PDF
        run: |
          gem install asciidoctor-pdf
          gem install rouge

      - name: Generate PDF
        run: |
          asciidoctor-pdf \
            -a allow-uri-read \
            README.adoc \
            -o README.pdf

      - name: Upload to release (if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: README.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare PDF for deployment
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p deploy
          cp README.pdf deploy/

      - name: Deploy PDF to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
          enable_jekyll: false
